#!/bin/bash
#

# If a fresh install based on the instructions in the README.md file, you can run the following commands to set up the environment.
# replace <your_username> with your actual username to set path correctly
#eval "$(/scratch/<your_username>/icomse_knam_session/miniconda3/bin/conda shell.bash hook)"
#conda activate
#source /usr/local/miniforge3/activate_conda_env.sh
#conda activate knamsessionenv

# ICOMSE on PSC: Set up environment variables for everything to work properly
# If not already loaded
# bash /ocean/projects/see220002p/shared/setupS25.sh 
# source ~/.bash_profile

# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7
charmm="mpirun -np 1 /ocean/projects/see220002p/shared/10th/charmm/charmm/c49b2_mdno97/bin/charmm" # replace <user_name> with your actual username 
equi_prefix="step4_equilibration"
qmpr_prefix="step4.1_qmmmprep"
prod_prefix="step5_production_dftb"
prod_step="step5_dftb"
qmpackage="sccdftb"

# Equilibration
#$charmm < "${equi_prefix}.inp" > "${equi_prefix}.out"

# QM/MM input preparation
#$charmm < "${qmpr_prefix}.inp" > "${qmpr_prefix}.out"

# Reaction Specs
rci=-2.0 #initial
rcf=2.0  #final
rcdel=0.1 #spacing
kmin=40 #40
kmax=150

rc_mid=$(awk "BEGIN {print (${rci} + ${rcf})/2}")
winmax=$(awk "BEGIN {print int(((${rcf} - ${rci})/${rcdel}) + 1)}")

# Production Specs
win=$1 #CHANGE HERE IF COUNTINUING STARTING WINDOW
winmax=${win} #UNCOMMENT IF RUNNING ONLY ONE WINDOW 
icnt=2  #CHANGE HERE IF COUNTINUING A RUN AT SPECIFIC COUNTER (CHUNK) IN ${win}
cntmax=2 #MAXIMUM NUMBER OF CHUNKS PER WINDOW
nstepp=500 # Number of MD steps per chunk


for ((i=$win;i<=$winmax;i++)); do
    cnt=${icnt} 
    while [ $cnt -le $cntmax ]; do
        pcnt=$(( cnt - 1 ))
        pwin=$(( i - 1 ))
        rc=$(awk "BEGIN {printf \"%.2f\", ${rci} + ((${i} - 1) * ${rcdel})}")
        scale=$(awk "BEGIN {printf \"%.6f\", 1 - ((2*($rc - $rc_mid)/($rcf - $rci))^2)}")
        kumb=$(awk "BEGIN {printf \"%.2f\", $kmin + ($kmax - $kmin)*$scale}")
        istep=${prod_step}_window_${i}_${cnt}

        
        if   [[ ${cnt} -eq 1 && ${i} -eq 1 ]]; then
            qrst=0
	        pstep=${equi_prefix}
        elif [[ ${cnt} -eq 1 && ${i} -gt 1 ]]; then
            qrst=1
            pstep=${prod_step}_window_${pwin}_${cntmax}
        elif [[ ${cnt} -gt 1  ]]; then
            qrst=1
            pstep=${prod_step}_window_${i}_${pcnt}
            cp step5_mndo97_window_${i}_${pcnt}.rst ${pstep}.rst
        fi

        $charmm mdnstepp=${nstepp} cnt=${cnt} mdcnt=${cnt} mdqrst=${qrst} mdwin=${i} mdpcnt=${pcnt} mdpwin=${pwin} mdrc=${rc} mdkumb=${kumb} mdpstep=${pstep} mdistep=${istep}  ${qmpackage}=1 < "${prod_prefix}.inp" > "${istep}.out"
        cnt=$(( cnt + 1 ))
    done
done 

